### ISSUE TITLE
Redundant download, %files warning, "bogus" date in RPM

### ISSUE THREAD

**Issue by gabrielgg** [rinigus/pkg-proj#1]
Hey, rinigus, just doing my EA build of OSM Scout Server and bumped into this, I guess the main question is the first one:
- Do we really need to execute download.sh to build proj here, given that you are linking to proj's github anyway? I've just built from proj.4 without a problem... or am I missing something?
- Build complains of duplicate %files - happy to fix+test this for you and submit a merge
- I have no idea why the build complains(warns) that the date in the changelog is bogus, I could try to resolve this, too but no promises as I don't know what the problem is with 10th April 2017, unless the build system ignores anything pre COVID </jk> :-)

**Comment by rinigus** [comment]
Re build: 

- I will make public tbuilder project that would allow to build maps stack easily. May take few days to set it up as repo, but can push this forward and make later today. Ideally, wait for it and try with tbuilder.

1: don't remember why we have download.sh. Could be just carried over from some older versions and probably can be removed
2: please fix %files
3: probably data and weekday don't match :)

**Comment by gabrielgg** [comment]
Thanks for the fast reply - OK, I can do both tbh - wait for tbuilder or do these 3 little fixes in parallel. I'll need some time to test/build myself, so maybe you will get there first.
PS: ah, didn't think about weekday, I used to pay attention to them in the before time when one wasn't at home every day :D (OK, I'll stop now with pandemic references).

**Comment by rinigus** [comment]
Sure, the bugfixes will be handy anyway :)

**Comment by rinigus** [comment]
TBuilder project initial version is at https://github.com/rinigus/tbuilder-maps

I haven't compiled all using this one yet, compilation is going on. We can maybe discuss it on #sailfishos freenode channel if you need help with tbuilder.

**Comment by gabrielgg** [comment]
Thanks, rinigus :) You beat me to it and won't need to build OSM Scout Server; however I'll check tbuilder and will reach out in #sailfishos at freenode.
Created merge request for the things mentioned here and a fourth detail that affects the README only: https://github.com/rinigus/pkg-proj/pull/2

**Comment by rinigus** [comment]
PR merged, closing it here
